# Generated by Django 5.2 on 2025-04-27 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KargoFirmasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255, unique=True)),
                ('etkin_mi', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='KargoUcreti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desi', models.PositiveIntegerField()),
                ('ucret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kargo_firmasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ucretler', to='kargo.kargofirmasi')),
            ],
            options={
                'ordering': ['kargo_firmasi', 'desi'],
                'unique_together': {('kargo_firmasi', 'desi')},
            },
        ),
    ]
