# Generated by Django 5.2 on 2025-04-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kargo', '0002_kargovergiorani'),
    ]

    operations = [
        migrations.AddField(
            model_name='kargofirmasi',
            name='desi_bolme_faktoru',
            field=models.DecimalField(blank=True, decimal_places=2, default=3000.0, max_digits=10, null=True),
        ),
    ]
