# Generated by Django 5.2 on 2025-05-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kargo', '0003_kargofirmasi_desi_bolme_faktoru'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kargofirmasi',
            options={'verbose_name': 'Kargo İşletmesi', 'verbose_name_plural': 'Kargo İşletmeleri'},
        ),
        migrations.AlterModelOptions(
            name='kargoucreti',
            options={'ordering': ['kargo_firmasi', 'desi'], 'verbose_name': 'Kargo Ücreti', 'verbose_name_plural': 'Kargo Ücretleri'},
        ),
        migrations.AlterModelOptions(
            name='kargovergiorani',
            options={'verbose_name': 'Kargo Vergisi Oranı', 'verbose_name_plural': 'Kargo Vergisi Oranları'},
        ),
    ]
