# Generated by Django 5.2 on 2025-05-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kargo', '0004_alter_kargofirmasi_options_alter_kargoucreti_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pazaryeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255, unique=True)),
                ('etkin_mi', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pazaryeri',
                'verbose_name_plural': 'Pazaryerleri',
            },
        ),
    ]
