# Generated by Django 5.2 on 2025-05-02 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kargo', '0005_pazaryeri'),
    ]

    operations = [
        migrations.AddField(
            model_name='kargoucreti',
            name='pazaryeri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pazaryeri_ucretleri', to='kargo.pazaryeri'),
        ),
        migrations.AlterField(
            model_name='kargoucreti',
            name='kargo_firmasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kargo_ucretleri', to='kargo.kargofirmasi'),
        ),
    ]
