# Generated by Django 5.2 on 2025-05-03 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kargo', '0006_kargoucreti_pazaryeri_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kargoucreti',
            unique_together={('kargo_firmasi', 'desi', 'pazaryeri')},
        ),
    ]
