# Generated by Django 5.2 on 2025-04-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kisi_tipi', models.CharField(choices=[('gercek', 'Gerçek Kişi'), ('tuzel', 'Tüzel Kişi')], max_length=10)),
                ('ad', models.CharField(blank=True, max_length=50, null=True)),
                ('soyad', models.CharField(blank=True, max_length=50, null=True)),
                ('tc_kimlik_no', models.CharField(blank=True, max_length=11, null=True)),
                ('sirket_adi', models.CharField(blank=True, max_length=100, null=True)),
                ('vergi_no', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
