# Generated by Django 5.2 on 2025-04-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisiler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KisiTuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
            ],
        ),
    ]
