# Generated by Django 5.2 on 2025-04-27 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisiler', '0002_kisituru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kisi',
            name='kisi_tipi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kisiler.kisituru'),
        ),
    ]
