# Generated by Django 5.2 on 2025-04-27 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kisiler', '0003_alter_kisi_kisi_tipi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kisi',
            old_name='kisi_tipi',
            new_name='kisi_turu',
        ),
    ]
