# Generated by Django 5.2 on 2025-04-27 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisiler', '0005_tuzelturu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kisituru',
            name='ad',
        ),
        migrations.AddField(
            model_name='kisi',
            name='tuzel_turu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kisiler.tuzelturu'),
        ),
        migrations.AddField(
            model_name='kisituru',
            name='adi',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kisi',
            name='ad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kisi',
            name='sirket_adi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kisi',
            name='soyad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kisi',
            name='vergi_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
