# Generated by Django 5.2 on 2025-04-27 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisiler', '0006_remove_kisituru_ad_kisi_tuzel_turu_kisituru_adi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kisi',
            name='kisi_turu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kisiler.kisituru'),
        ),
    ]
