# Generated by Django 5.2 on 2025-04-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255, unique=True)),
                ('en', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yukseklik', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agirlik', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
