# Generated by Django 5.2 on 2025-05-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0002_alter_urun_agirlik_alter_urun_boy_alter_urun_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urun',
            options={'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
    ]
